export const REGIONS_KO = [
  { id:'frontal', name:'전두엽', color:'#E8735A', bright:'#FF9070',
    pos:[0,0.3,0.88], scl:[1.4,1.0,1.05], r:0.60,
    symptom:'실행 기능 및 충동 제어',
    impact:'그릇 방치, 화장실 청소 건너뜀, 사회적 필터 없음',
    desc:'전두엽은 계획 수립, 의사결정, 충동 제어, 사회적 자기 모니터링을 담당합니다. 뇌졸중 후에는 행동을 순서화하고 제동 장치를 적용하는 회로가 물리적으로 손상됩니다. 가족분이 부주의하기로 선택하는 것이 아닙니다 — 뇌의 자기 조절 시스템 자체가 손상된 것입니다.',
    functions:['행동 순서화','충동 제어','자기 모니터링','사회적 판단','과제 시작'] },
  { id:'parietal', name:'두정엽', color:'#5B8DD9', bright:'#7AA8F0',
    pos:[0,0.98,-0.05], scl:[1.3,0.88,1.12], r:0.65,
    symptom:'병식불능증 — 자신의 결손 인식 불능',
    impact:'문제가 있다는 것을 진정으로 인식하지 못함',
    desc:'병식불능증은 자기 인식을 생성하는 우측 두정엽이 손상될 때 발생합니다. 이것은 부정이나 고집이 아닙니다. 뇌의 자기 모니터링 시스템 자체가 손상된 것입니다. 환자는 진정으로 자신의 결손이나 그 행동이 타인에게 미치는 영향을 인식할 수 없습니다.',
    functions:['자기 인식','신체 지각','공간 처리','주의력','자신의 결손 인식'] },
  { id:'temporal', name:'측두엽', color:'#5BBD8A', bright:'#6FD9A0',
    pos:[1.0,-0.05,0.1], scl:[0.70,1.05,1.2], r:0.58,
    symptom:'기억 및 언어 이해',
    impact:'지시가 기억되지 않음; 말로 하는 요청이 인식되지 않을 수 있음',
    desc:'측두엽은 기억 형성, 언어 이해, 인식을 처리합니다. 손상되면 새로운 지시가 저장되지 않을 수 있고, 말로 하는 요청이 완전히 처리되지 않을 수 있으며, 환자가 듣고 있는 것처럼 보여도 익숙한 일과를 기억하기 어려워집니다.',
    functions:['단기 기억','언어 이해','지시 따르기','사물 인식','새로운 패턴 학습'] },
  { id:'occipital', name:'후두엽', color:'#9B6FD9', bright:'#B485F0',
    pos:[0,0.2,-1.02], scl:[1.05,0.9,0.85], r:0.58,
    symptom:'시야 및 사물 처리',
    impact:'인식하지 못하는 맹점이 있을 수 있음 — 가까운 물건을 놓침',
    desc:'후두엽은 모든 시각 정보를 처리합니다. 뇌졸중 손상은 환자가 모르는 시야 장애(맹점)를 유발하거나 사물 인식 및 깊이 지각 장애를 일으킵니다. 환자가 알아차리지 못한 채 물건에 부딪히거나 놓치는 이유를 설명합니다.',
    functions:['전체 시야','사물 인식','깊이 지각','읽기','시각 추적'] },
  { id:'cerebellum', name:'소뇌', color:'#D9A84E', bright:'#F0BF5A',
    pos:[0,-0.65,-0.52], scl:[1.2,0.72,0.9], r:0.56,
    symptom:'균형 및 운동 협응',
    impact:'정밀한 작업의 신체적 어려움 — 쏟거나 흘리는 것이 실재함',
    desc:'소뇌는 움직임, 균형, 미세 운동 제어를 조정합니다. 손상되면 접시 나르기, 화장실 위생 관리, 정밀한 신체 동작과 같은 작업이 진정으로 어려워집니다. 일부 지저분함은 무관심이 아닌 협응 장애를 반영합니다.',
    functions:['균형','미세 운동 제어','협응된 움직임','보행 안정성','시간 맞춘 동작'] },
  { id:'limbic', name:'변연계', color:'#D96F8A', bright:'#F080A0',
    pos:[0,0.0,-0.05], scl:[0.78,0.78,0.78], r:0.48,
    symptom:'감정, 공감 및 사회적 유대',
    impact:'가족의 감정을 신경 쓰지 않는 것처럼 보일 수 있음',
    desc:'변연계는 감정 경험, 공감, 사회적 연결을 처리합니다. 뇌졸중 손상은 감정 반응을 둔하게 하고 공감 능력을 감소시킵니다. 이것은 감정 회로에 대한 신경학적 손상이며, 그 사람의 성격 변화가 아닙니다.',
    functions:['공감','감정 표현','사회적 유대','동기','감정 기억'] },
];

export const HEROES_KO = [
  { name:'Jill Bolte Taylor 박사', role:'하버드 신경해부학자 & 뇌졸중 생존자',
    book:'뇌과학자의 뇌졸중 회고 (2008)', color:'#E8735A',
    quote:'뇌졸중이 나에게 일어날 수 있는 최고의 일이었다는 것을 깨달았습니다.',
    why:'37세에 대규모 뇌졸중을 앓고 8년간 회복한 뇌과학자입니다. 그녀의 TED 강연은 가장 많이 시청된 강연 중 하나가 되었습니다. 그녀는 간병인들에게 손상된 뇌가 실제로 세상을 어떻게 경험하는지 내부에서 가르쳐줍니다.',
    link:'https://www.ted.com/talks/jill_bolte_taylor_my_stroke_of_insight' },
  { name:'Debra Meyerson', role:'스탠퍼드 교수 & 뇌졸중 생존자',
    book:'정체성 도둑: 뇌졸중 후 자신을 재발견하기 (2021)', color:'#5B8DD9',
    quote:'뇌졸중이 나의 정체성을 훔쳐갔습니다. 회복은 더 풍요로운 정체성을 주었습니다.',
    why:'53세에 뇌졸중 후 언어와 직업 정체성을 잃은 스탠퍼드 교수입니다. 그녀와 남편은 뇌 손상 후 가족이 정체성을 재건하도록 돕기 위해 Stroke Onward를 공동 설립했습니다.',
    link:'https://strokeonward.org' },
  { name:'Jean-Dominique Bauby', role:'프랑스 Elle 편집장, 감금 증후군 생존자',
    book:'잠수종과 나비 (1997)', color:'#9B6FD9',
    quote:'내 고치가 덜 답답해지고, 내 마음은 나비처럼 날아오릅니다.',
    why:'대규모 뇌졸중 후 왼쪽 눈만 제외하고 마비된 채, 바비는 눈 깜박임으로 전체 회고록을 구술했습니다. 사랑하는 사람이 아직 거기 있는지 궁금해하는 가족을 위해 — 이 책은 강력하게 대답합니다: 네.',
    link:'https://en.wikipedia.org/wiki/The_Diving_Bell_and_the_Butterfly' },
  { name:'Norman Doidge 의학박사', role:'정신과 의사 & 신경가소성 연구자',
    book:'스스로 변화하는 뇌 (2007)', color:'#5BBD8A',
    quote:'뇌는 우리가 한때 생각했던 변하지 않는 기관이 아닙니다.',
    why:'도지는 목표 연습을 통해 뇌를 재배선한 수십 가지 뇌졸중 생존자 사례를 기록했습니다. 가족에게 희망의 과학적 근거를 제공하고 재활과 일관된 일과가 신경학적 수준에서 실제로 작동하는 이유를 설명합니다.',
    link:'https://www.normandoidge.com' },
  { name:'Mona & Stacy Gupton', role:'어머니와 딸 — 간병인 & 생존자',
    book:'그녀의 기억 조각: 뇌졸중과 회복을 통한 모녀 여정', color:'#D9A84E',
    quote:'우리는 뇌졸중의 반대편에서 서로를 다시 찾았습니다.',
    why:'간병인과 생존자의 관점 모두에서 동시에 쓰여진 책입니다. 변화된 관계의 슬픔을 경험하는 가족에게 드물고 소중합니다.',
    link:'https://unitedstrokealliance.org/resources/books' },
  { name:'Tsgoyna Tanzman, SLP', role:'언어병리학자 & 간병인 옹호자',
    book:'뇌졸중 후의 희망: 재활 및 간병인 가이드북', color:'#D96F8A',
    quote:'희망은 희망사항적 생각이 아닙니다. 의도적인 실천입니다.',
    why:'실용적이고, 전체적이며, 깊이 공감적입니다. 탄츠만은 감정적 세계와 임상 세계를 연결합니다 — 언어, 인지, 영양, 친밀감, 영성을 다룹니다.',
    link:'https://thenewgait.com/blog/6-best-books-on-stroke-recovery-in-2023/' },
];

export const WELLBEING_KO = [
  { skill:'자기 연민', icon:'🤲', color:'#E8735A',
    why:'간병인에게 가장 큰 영향을 미치는 단일 기술입니다. 대부분의 가족 구성원은 깊이 자기비판적입니다. 자기 연민은 이 사이클을 과학적으로 끊어줍니다.',
    how:'Kristin Neff의 자기 연민 (책 + self-compassion.org의 무료 연습). 실천: 가슴에 손을 얹고 "이것은 어렵습니다. 나만 이런 것이 아닙니다. 나 자신에게 친절하게 대하기를."이라고 말하기.',
    time:'하루 5분', level:'초보자',
    link:'https://self-compassion.org', linkLabel:'self-compassion.org' },
  { skill:'마음챙김 명상', icon:'🧘', color:'#5B8DD9',
    why:'간병인의 코르티솔 수준을 줄이고, 감정 조절을 개선하며, 번아웃을 감소시킵니다. 하루 10분만으로도 8주 안에 측정 가능한 신경학적 변화가 생깁니다.',
    how:'앱: Insight Timer (무료), Headspace, Calm. 바디 스캔 명상으로 시작하세요. MBSR 8주 프로그램은 간병인을 위한 증거 기반 방법입니다.',
    time:'하루 10-20분', level:'초보자 → 중급',
    link:'https://www.insighttimer.com', linkLabel:'Insight Timer' },
  { skill:'회복 요가', icon:'🌿', color:'#5BBD8A',
    why:'만성적인 간병이 몸을 싸움-도피 반응에 고착시킨 후 부교감 신경계를 활성화합니다. 회복 요가는 수행이 아닌 이완에 관한 것입니다.',
    how:'유튜브: Yoga with Adriene (무료). 취침 전 15분 바닥 자세가 수면의 질을 변화시킵니다.',
    time:'주 3회, 15-30분', level:'전 레벨',
    link:'https://www.youtube.com/yogawithadriene', linkLabel:'Yoga with Adriene' },
  { skill:'신체 중심 실천', icon:'🌊', color:'#9B6FD9',
    why:'간병 트라우마는 마음뿐만 아니라 몸에 저장됩니다. 신체 중심 실천은 마음챙김만으로는 도달할 수 없는 신체적 긴장 패턴을 풀어줍니다.',
    how:'EFT 태핑 (무료 유튜브 튜토리얼). TRE (트라우마 해소 운동). 이것들은 간병이 지속적으로 방해하는 스트레스 반응 사이클을 완성시킵니다.',
    time:'필요에 따라 10-20분', level:'초보자',
    link:'https://www.eftuniverse.com', linkLabel:'EFT Universe' },
  { skill:'슬픔 일기 쓰기', icon:'📝', color:'#D9A84E',
    why:'모호한 슬픔 — 아직 살아있는 사람을 애도하는 것 — 은 가장 이해받지 못하는 상실의 형태 중 하나입니다. 종이에 이름 붙이는 것이 그 힘을 줄입니다.',
    how:'프롬프트: "내가 가장 그리운 사람은..." / "화가 나는 것과 그것이 괜찮은 이유..." / "오늘의 은혜로운 순간은..." 독자 없이, 다듬지 않고.',
    time:'주 3-4회, 10-15분', level:'전 레벨',
    link:'https://www.paulineboss.com', linkLabel:'Pauline Boss — 모호한 상실' },
  { skill:'자연 노출 (산림욕)', icon:'🌲', color:'#D96F8A',
    why:'자연에서 20분은 코르티솔, 혈압, 염증 수치를 낮춥니다. 일본 산림욕은 현재 여러 나라에서 의사들이 처방합니다.',
    how:'목적지 없이 걸으세요. 이것은 운동이 아니라 신경계 치료입니다.',
    time:'주 2-3회, 20분', level:'전 레벨',
    link:'https://www.shinrin-yoku.org', linkLabel:'Shinrin-yoku.org' },
  { skill:'커뮤니티 의식', icon:'🕯️', color:'#E8C890',
    why:'고립은 간병인 건강의 조용한 파괴자입니다. 구조화된 커뮤니티는 사회적 신경계를 재건합니다.',
    how:'단 한 명의 다른 사람과도 주간 의식: 통화, 산책, 식사. 지원 그룹도 포함됩니다. 빈도보다 규칙성이 중요합니다.',
    time:'주간, 타협 불가', level:'전 레벨',
    link:'https://strokeonward.org/community', linkLabel:'Stroke Onward 커뮤니티' },
  { skill:'경계 실천', icon:'⚓', color:'#8AB4D9',
    why:'많은 간병인들이 부서질 때까지 모든 것에 예라고 합니다. 경계는 이기적인 것이 아닙니다 — 지속 가능한 돌봄의 구조입니다.',
    how:'책: Nedra Tawwab의 경계를 설정하고 평화를 찾아라. 주당 하나의 경계로 시작하세요.',
    time:'지속적인 실천', level:'중급',
    link:'https://nedratawwab.com', linkLabel:'Nedra Tawwab' },
];

export const IOT_SOLUTIONS_KO = [
  { title:'낙상 감지 시스템', icon:'🛡️', color:'#E8735A', difficulty:'DIY 가능',
    desc:'웨어러블 가속도계 + 자이로스코프 (ESP32의 MPU6050)가 갑작스러운 낙상을 감지하고 가족 전화로 즉시 SMS/앱 알림을 보냅니다.',
    impact:'24시간 7일 물리적으로 옆에 있어야 할 필요성을 없애줍니다. 낙상 후 수 초 내에 가족이 알림을 받습니다.',
    hardware:['ESP32 또는 라즈베리파이','MPU6050 가속도계','WiFi 모듈','선택사항: 손목밴드 케이스'] },
  { title:'화장실 재실 모니터', icon:'🚿', color:'#5B8DD9', difficulty:'쉬운 DIY',
    desc:'PIR 동작 센서 + 도어 접촉 센서가 화장실 출입을 추적합니다. 너무 오래 점유되거나 정해진 시간에 방문하지 않으면 알림을 보냅니다. 완전히 프라이버시 보호 — 카메라 없음.',
    impact:'가족 스트레스의 가장 일반적인 원인을 직접 해결합니다. 감시 없는 수동적 모니터링.',
    hardware:['PIR 동작 센서','자석 도어 센서','ESP8266/ESP32','Home Assistant 또는 MQTT'] },
  { title:'스마트 약 복용 알림', icon:'💊', color:'#5BBD8A', difficulty:'상용 제품',
    desc:'자동화된 알약 분배기 (MedMinder, Hero)가 일정에 맞춰 약을 방출하고, 복용량을 놓치면 가족에게 알립니다.',
    impact:'약 복용 순응도는 회복에 극적인 영향을 미칩니다. 약에 관한 일상적인 가족 갈등을 없애줍니다.',
    hardware:['MedMinder 또는 Hero 기기','WiFi 연결','가족 앱 구독'] },
  { title:'자동 야간 조명', icon:'🌙', color:'#D9A84E', difficulty:'쉬운 DIY',
    desc:'침대 아래 압력 매트 + 동작 센서가 환자가 밤에 일어날 때 부드러운 바닥 조명을 켭니다.',
    impact:'야간 낙상이 가장 위험합니다. 이 하나의 변화가 심각한 부상을 예방하고 가족의 불안을 줄입니다.',
    hardware:['압력 매트 센서','LED 스트립','ESP32','5V 릴레이 모듈'] },
  { title:'활동 패턴 모니터', icon:'📊', color:'#9B6FD9', difficulty:'중급 DIY',
    desc:'수동 PIR 센서 네트워크가 일반적인 일상 루틴의 지도를 만듭니다. 패턴이 깨질 때 가족에게 알립니다.',
    impact:'인지 저하, 질병, 안전하지 않은 행동에 대한 조기 경보 시스템. 완전히 비침습적.',
    hardware:['다수의 PIR 센서','라즈베리파이 허브','Home Assistant','MQTT 브로커'] },
  { title:'음성 제어 스마트 홈', icon:'🎙️', color:'#D96F8A', difficulty:'상용 제품',
    desc:'Amazon Echo 또는 Google Nest를 사용하면 뇌졸중 생존자가 음성 명령으로 조명, 온도를 제어하고 가족에게 전화할 수 있습니다.',
    impact:'독립성과 존엄성을 회복합니다. 기본적인 요청으로 인한 가족 부담을 줄입니다.',
    hardware:['Amazon Echo 또는 Google Nest Hub','스마트 플러그','스마트 전구','루틴 설정'] },
  { title:'공기질 및 환경 모니터링', icon:'🌬️', color:'#5BD9C8', difficulty:'쉬운 DIY',
    desc:'온도, 습도, CO2 센서가 생활 공간의 안전을 보장합니다. ESP32 + DHT22 + MQ135로 15달러 미만.',
    impact:'환경 요인이 신경학적 회복에 직접적인 영향을 미칩니다. 만들기 쉽고 영향력이 높습니다.',
    hardware:['DHT22 온도/습도 센서','MQ135 CO2 센서','ESP32','OLED 디스플레이 + 알림'] },
  { title:'통합 간병인 대시보드', icon:'🖥️', color:'#E8D06A', difficulty:'중급',
    desc:'모든 센서가 Home Assistant 또는 맞춤형 React 대시보드를 실행하는 라즈베리파이로 연결됩니다.',
    impact:'분산된 불안을 실행 가능한 인식으로 변환합니다. 원격의 가족 구성원도 간병에 참여할 수 있습니다.',
    hardware:['라즈베리파이 4','Home Assistant','React UI (선택사항)','위의 모든 센서'] },
];

export const BUILDER_PROJECTS_KO = [
  { title:'ESP32 화장실 안전 시스템', phase:'Phase 1 — 여기서 시작', color:'#E8735A',
    skills:['ESP32 프로그래밍 (C/Arduino)','PIR 및 도어 센서','WiFi/MQTT','Twilio 또는 Pushover SMS 알림'],
    desc:'이 가족의 즉각적인 문제를 직접 해결합니다. PIR + 도어 센서가 화장실 사용을 모니터링하고 패턴이 비정상적이면 SMS로 알립니다. 제작 시간: 1-2주말.',
    why:'현재 임베디드 시스템 기술로 최대의 실제 효과. ESP32는 정확히 당신이 배우고 있는 것입니다. 진정한 인도주의적 목적을 가진 포트폴리오 프로젝트입니다.',
    steps:['ESP32에 PIR + 도어 접촉 센서 연결','재실 로직이 있는 Arduino 펌웨어 플래시','WiFi 및 MQTT 브로커 연결','SMS 알림을 위한 Twilio 설정','화장실에 설치, 가족과 테스트'] },
  { title:'낙상 감지 손목밴드', phase:'Phase 2 — 중급', color:'#5B8DD9',
    skills:['ESP32 + MPU6050 I2C','신호 처리 (임계값 감지)','BLE 또는 WiFi 통신','3D 프린팅 또는 폼 케이스'],
    desc:'가속도계가 있는 웨어러블 기기. 낙상과 일치하는 갑작스러운 가속도 변화를 감지합니다. 즉시 가족 전화에 알림을 보냅니다.',
    why:'MPU6050은 IoT/임베디드 경로의 표준 센서입니다. 이 프로젝트는 I2C, 신호 처리, 실시간 엣지 컴퓨팅을 가르쳐줍니다.',
    steps:['I2C를 통해 ESP32와 MPU6050 인터페이스','낙상 감지 임계값 보정','전화기로 BLE 알림 구현','편안한 웨어러블 케이스 설계','가족과 테스트 및 보정'] },
  { title:'통합 가족 대시보드', phase:'Phase 3 — 풀 스택', color:'#5BBD8A',
    skills:['MQTT 브로커 (Mosquitto)','React 프론트엔드','Node.js 또는 Python 백엔드','라즈베리파이 배포'],
    desc:'모든 센서가 Home Assistant + 맞춤형 React 대시보드를 실행하는 라즈베리파이로 연결됩니다. 가족 구성원이 어떤 전화에서도 실시간 상태를 봅니다.',
    why:'IoT 하드웨어 기술을 소프트웨어 기술과 연결합니다. 라즈베리파이에서의 실제 배포 — 풀 스택 IoT 엔지니어가 되게 하는 임베디드 Linux 작업입니다.',
    steps:['라즈베리파이에서 Mosquitto MQTT 설정','모든 ESP32 센서를 MQTT 퍼블리셔로 연결','실시간 업데이트가 있는 React 대시보드 제작','로컬 네트워크 + Tailscale에 배포','가족과 공유 — 피드백 기반으로 반복'] },
  { title:'스마트 팜 → 치유 정원', phase:'Phase 4 — 비전', color:'#D9A84E',
    skills:['환경 센서 (스마트 팜과 동일)','식물 치료 모니터링','AI 이상 감지','오픈소스 커뮤니티 플랫폼'],
    desc:'스마트 팜 센서 툴킷은 치료적 홈 환경 모니터링과 거의 직접적으로 연결됩니다. 뇌졸중 회복을 위한 치유 정원 공간.',
    why:'이것이 당신의 솔라펑크 비전과 이 가족의 필요가 교차하는 지점입니다. 치료 정원은 뇌졸중 회복에 입증된 효과가 있습니다.',
    steps:['재배 환경 센서를 생활 공간에 적용','간병인 대시보드에 식물 모니터링 추가','뇌졸중 회복을 위한 원예 치료 연구','다른 가족들을 위한 오픈소스 프로젝트로 문서화','블로그에 사례 연구로 게시'] },
];
