export const REGIONS = [
  { id:"frontal", name:"Frontal Lobe", color:"#E8735A", bright:"#FF9070",
    pos:[0,0.3,0.88], scl:[1.4,1.0,1.05], r:0.60,
    symptom:"Executive Function & Impulse Control",
    impact:"Leaving plates dirty, skipping bathroom cleanup, no social filtering",
    desc:"The frontal lobe governs planning, decision-making, impulse control, and social self-monitoring. After stroke, the circuits that sequence actions and apply behavioral brakes are physically damaged. Your loved one isn't choosing to be careless — the brain's self-regulation system is injured.",
    functions:["Action sequencing","Impulse control","Self-monitoring","Social judgment","Task initiation"]},
  { id:"parietal", name:"Parietal Lobe", color:"#5B8DD9", bright:"#7AA8F0",
    pos:[0,0.98,-0.05], scl:[1.3,0.88,1.12], r:0.65,
    symptom:"Anosognosia — Unawareness of Own Deficits",
    impact:"Genuinely cannot perceive that they have a problem",
    desc:"Anosognosia occurs when the right parietal cortex — the region that generates self-awareness — is damaged. This is not denial or stubbornness. The brain's self-monitoring system is itself the injury. The person truly cannot perceive their deficits or recognize how their behavior affects others.",
    functions:["Self-awareness","Body perception","Spatial processing","Attention","Recognizing own deficits"]},
  { id:"temporal", name:"Temporal Lobe", color:"#5BBD8A", bright:"#6FD9A0",
    pos:[1.0,-0.05,0.1], scl:[0.70,1.05,1.2], r:0.58,
    symptom:"Memory & Language Comprehension",
    impact:"Instructions aren't retained; spoken requests may not register",
    desc:"The temporal lobes handle memory formation, language comprehension, and recognition. Damage means new instructions may not be stored, spoken requests may not fully process, and familiar routines become difficult to recall — even when the person appears to be listening.",
    functions:["Short-term memory","Language comprehension","Following instructions","Object recognition","Learning new patterns"]},
  { id:"occipital", name:"Occipital Lobe", color:"#9B6FD9", bright:"#B485F0",
    pos:[0,0.2,-1.02], scl:[1.05,0.9,0.85], r:0.58,
    symptom:"Visual Field & Object Processing",
    impact:"May have blind spots they're unaware of — missing objects nearby",
    desc:"The occipital lobe processes all visual information. Stroke damage can cause visual field cuts — blind spots the person may not know exist — as well as difficulty with object recognition and depth perception. This explains why things are bumped into or missed without the person noticing.",
    functions:["Full visual field","Object recognition","Depth perception","Reading","Visual tracking"]},
  { id:"cerebellum", name:"Cerebellum", color:"#D9A84E", bright:"#F0BF5A",
    pos:[0,-0.65,-0.52], scl:[1.2,0.72,0.9], r:0.56,
    symptom:"Balance & Motor Coordination",
    impact:"Physical difficulty with precise tasks — spills and messes are real",
    desc:"The cerebellum coordinates movement, balance, and fine motor control. When damaged, tasks like carrying dishes, managing bathroom hygiene, or precise physical actions become genuinely difficult. Some messes reflect coordination impairment — not indifference.",
    functions:["Balance","Fine motor control","Coordinated movement","Gait stability","Timed actions"]},
  { id:"limbic", name:"Limbic System", color:"#D96F8A", bright:"#F080A0",
    pos:[0,0.0,-0.05], scl:[0.78,0.78,0.78], r:0.48,
    symptom:"Emotion, Empathy & Social Bonding",
    impact:"May seem not to care about family members' feelings",
    desc:"The limbic system processes emotional experience, empathy, and social connection. Stroke damage here blunts emotional responses and reduces the capacity for empathy. This is neurological damage to the emotional circuitry, not a change in the person's character.",
    functions:["Empathy","Emotional expression","Social bonding","Motivation","Emotional memory"]},
];

export const HEROES = [
  { name:"Jill Bolte Taylor, Ph.D.", role:"Harvard Neuroanatomist & Stroke Survivor",
    book:"My Stroke of Insight (2008)", color:"#E8735A",
    quote:"I realized the stroke was the best thing that could have happened to me.",
    why:"A brain scientist who suffered a massive stroke at 37 and spent 8 years recovering. Her TED Talk became one of the most watched of all time. She teaches caregivers how the injured brain actually experiences the world — from the inside.",
    link:"https://www.ted.com/talks/jill_bolte_taylor_my_stroke_of_insight"},
  { name:"Debra Meyerson", role:"Stanford Professor & Stroke Survivor",
    book:"Identity Theft: Rediscovering Ourselves After Stroke (2021)", color:"#5B8DD9",
    quote:"Stroke stole my identity. Recovery gave me a richer one.",
    why:"A Stanford professor who lost her speech and career identity after stroke at 53. She and her husband co-founded Stroke Onward to help families rebuild identity after brain injury. Deeply relevant for families grieving the person their loved one used to be.",
    link:"https://strokeonward.org"},
  { name:"Jean-Dominique Bauby", role:"Editor of French Elle, Locked-In Syndrome Survivor",
    book:"The Diving Bell and the Butterfly (1997)", color:"#9B6FD9",
    quote:"My cocoon becomes less oppressive, and my mind takes flight like a butterfly.",
    why:"Paralyzed except for his left eye after a massive stroke, Bauby dictated an entire memoir by blinking. For families who wonder if their loved one is still 'in there' — this book answers powerfully: yes.",
    link:"https://en.wikipedia.org/wiki/The_Diving_Bell_and_the_Butterfly"},
  { name:"Norman Doidge, M.D.", role:"Psychiatrist & Neuroplasticity Researcher",
    book:"The Brain That Changes Itself (2007)", color:"#5BBD8A",
    quote:"The brain is not the unchanging organ we once thought it was.",
    why:"Doidge documented dozens of cases of stroke survivors who rewired their brains through targeted practice. Gives families a scientific basis for hope — and explains why rehabilitation and consistent routine actually work at the neurological level.",
    link:"https://www.normandoidge.com"},
  { name:"Mona & Stacy Gupton", role:"Mother & Daughter — Caregiver & Survivor",
    book:"A Piece of Her Mind: A Mother-Daughter Journey Through Stroke and Recovery", color:"#D9A84E",
    quote:"We found each other again on the other side of the stroke.",
    why:"Written from both the caregiver's and the survivor's perspective simultaneously. Rare and vital for families experiencing the grief of changed relationships.",
    link:"https://unitedstrokealliance.org/resources/books"},
  { name:"Tsgoyna Tanzman, SLP", role:"Speech-Language Pathologist & Caregiver Advocate",
    book:"Hope After Stroke: The Rehabilitation and Nursing/Caregiver Guidebook", color:"#D96F8A",
    quote:"Hope is not wishful thinking. It is a deliberate practice.",
    why:"Practical, holistic, and deeply empathetic. Tanzman bridges the emotional and clinical worlds — covering speech, cognition, nutrition, intimacy, and spirituality. An indispensable companion for families.",
    link:"https://thenewgait.com/blog/6-best-books-on-stroke-recovery-in-2023/"},
];

export const WELLBEING = [
  { skill:"Self-Compassion", icon:"🤲", color:"#E8735A",
    why:"The single highest-impact skill for caregivers. Most family members are deeply self-critical. Self-compassion breaks this cycle scientifically.",
    how:"Kristin Neff's Self-Compassion (book + free exercises at self-compassion.org). Practice: place hand on heart, say 'This is hard. I'm not alone in this. May I be kind to myself.'",
    time:"5 min/day", level:"Beginner"},
  { skill:"Mindfulness Meditation", icon:"🧘", color:"#5B8DD9",
    why:"Reduces caregiver cortisol levels, improves emotional regulation, and decreases burnout. Even 10 minutes daily creates measurable neurological change within 8 weeks.",
    how:"Apps: Insight Timer (free), Headspace, Calm. Start with body scan meditations. The MBSR 8-week program is evidence-based for caregivers.",
    time:"10–20 min/day", level:"Beginner → Intermediate"},
  { skill:"Restorative Yoga", icon:"🌿", color:"#5BBD8A",
    why:"Activates the parasympathetic nervous system after chronic caregiving keeps the body stuck in fight-or-flight. Restorative yoga is about releasing, not performing.",
    how:"YouTube: Yoga with Adriene (free). In Wauwatosa: local studios. Floor poses for 15 min before bed transforms sleep quality.",
    time:"15–30 min, 3x/week", level:"All levels"},
  { skill:"Somatic Practices", icon:"🌊", color:"#9B6FD9",
    why:"Caregiving trauma is stored in the body, not just the mind. Somatic practices release physical tension patterns that mindfulness alone cannot reach.",
    how:"EFT tapping (free YouTube tutorials). TRE (Trauma Release Exercises). Shaking practice. These complete the stress response cycle that caregiving perpetually interrupts.",
    time:"10–20 min as needed", level:"Beginner"},
  { skill:"Grief Journaling", icon:"📝", color:"#D9A84E",
    why:"Ambiguous grief — grieving someone who is still alive — is one of the least understood forms of loss. Naming it on paper reduces its power over daily life.",
    how:"Prompts: 'The person I miss most is...' / 'What I'm angry about and why that's okay...' / 'One moment of grace today was...' No audience, no polish.",
    time:"10–15 min, 3–4x/week", level:"All levels"},
  { skill:"Nature Exposure (Shinrin-yoku)", icon:"🌲", color:"#D96F8A",
    why:"20 minutes in nature lowers cortisol, blood pressure, and inflammatory markers. Japanese forest bathing is now prescribed by physicians in multiple countries.",
    how:"Wauwatosa has Menomonee River Parkway nearby. Walk without destination. This is nervous system medicine, not exercise.",
    time:"20 min, 2–3x/week", level:"All levels"},
  { skill:"Community Ritual", icon:"🕯️", color:"#E8C890",
    why:"Isolation is the silent destroyer of caregiver health. Structured community — not just occasional contact — rebuilds the social nervous system.",
    how:"A weekly ritual with even one other person: a call, a walk, a meal. Support groups count. Regularity matters more than frequency.",
    time:"Weekly, non-negotiable", level:"All levels"},
  { skill:"Boundary Practice", icon:"⚓", color:"#8AB4D9",
    why:"Many caregivers say yes to everything until they break. Boundaries aren't selfish — they are the architecture of sustainable care.",
    how:"Book: Set Boundaries, Find Peace by Nedra Tawwab. Start with one boundary per week. Practice the discomfort of saying no until it becomes normal.",
    time:"Ongoing practice", level:"Intermediate"},
];

export const IOT_SOLUTIONS = [
  { title:"Fall Detection System", icon:"🛡️", color:"#E8735A", difficulty:"DIY Possible",
    desc:"Wearable accelerometer + gyroscope (MPU6050 on ESP32) detects sudden falls and sends immediate SMS/app alert to family.",
    impact:"Removes need for someone to be physically present 24/7. Family gets alerted within seconds of a fall.",
    hardware:["ESP32 or Raspberry Pi","MPU6050 accelerometer","WiFi module","Optional: wristband enclosure"]},
  { title:"Bathroom Occupancy Monitor", icon:"🚿", color:"#5B8DD9", difficulty:"Easy DIY",
    desc:"PIR motion sensor + door contact sensor tracks bathroom entry/exit. Sends alert if occupied too long or not visited on schedule. Completely privacy-safe — no camera.",
    impact:"Directly addresses the most common source of family distress. Passive monitoring without surveillance.",
    hardware:["PIR motion sensor","Magnetic door sensor","ESP8266/ESP32","Home Assistant or MQTT"]},
  { title:"Smart Medication Reminder", icon:"💊", color:"#5BBD8A", difficulty:"Commercial",
    desc:"Automated pill dispensers (MedMinder, Hero) release medication on schedule, alert family if doses are missed.",
    impact:"Medication adherence dramatically affects recovery. Eliminates daily family conflict around pills.",
    hardware:["MedMinder or Hero device","WiFi connection","Family app subscription"]},
  { title:"Automatic Night Lighting", icon:"🌙", color:"#D9A84E", difficulty:"Easy DIY",
    desc:"Pressure mat under bed + motion sensor triggers soft floor lighting when patient gets up at night. Luna Lights commercial or DIY with LED strip + ESP32.",
    impact:"Nighttime falls are most dangerous. This one change prevents significant injury and reduces family anxiety.",
    hardware:["Pressure mat sensor","LED strip","ESP32","5V relay module"]},
  { title:"Activity Pattern Monitor", icon:"📊", color:"#9B6FD9", difficulty:"Intermediate DIY",
    desc:"Network of passive PIR sensors builds a map of normal daily routines. Flags when pattern breaks — 'Dad usually reaches the kitchen by 9am.' Alerts family if not.",
    impact:"Early warning system for cognitive decline, illness, or unsafe behavior. Completely non-invasive.",
    hardware:["Multiple PIR sensors","Raspberry Pi hub","Home Assistant","MQTT broker"]},
  { title:"Voice-Activated Smart Home", icon:"🎙️", color:"#D96F8A", difficulty:"Commercial",
    desc:"Amazon Echo or Google Nest allows stroke survivor to control lights, temperature, and call family with voice commands.",
    impact:"Restores independence and dignity. Reduces family burden from basic requests.",
    hardware:["Amazon Echo or Google Nest Hub","Smart plugs","Smart bulbs","Routine programming"]},
  { title:"Air Quality & Environment", icon:"🌬️", color:"#5BD9C8", difficulty:"Easy DIY",
    desc:"Temperature, humidity, and CO2 sensors ensure the living space is safe. Extreme temperatures are particularly dangerous post-stroke. ESP32 + DHT22 + MQ135 under $15.",
    impact:"Environmental factors directly affect neurological recovery. Simple to build, high impact.",
    hardware:["DHT22 temp/humidity","MQ135 CO2 sensor","ESP32","OLED display + alerts"]},
  { title:"Unified Caregiver Dashboard", icon:"🖥️", color:"#E8D06A", difficulty:"Intermediate",
    desc:"All sensors feed into Home Assistant or a custom React dashboard. Family members monitor remotely. Real-time: 'Dad last moved at 2:34pm, bathroom visited at 3:10pm.'",
    impact:"Transforms scattered anxiety into actionable awareness. Remote family members can participate in caregiving.",
    hardware:["Raspberry Pi 4","Home Assistant","React UI (optional)","All sensors above"]},
];

export const BUILDER_PROJECTS = [
  { title:"ESP32 Bathroom Safety System", phase:"Phase 1 — Start Here", color:"#E8735A",
    skills:["ESP32 programming (C/Arduino)","PIR & door sensors","WiFi/MQTT","Twilio or Pushover SMS alerts"],
    desc:"Directly solves this family's immediate problem. PIR + door sensor monitors bathroom usage and alerts via SMS if patterns are abnormal. Build time: 1–2 weekends.",
    why:"Maximum real-world impact with current embedded systems skills. ESP32 is exactly what you're learning. This is a portfolio project with genuine humanitarian purpose.",
    steps:["Wire PIR + door contact to ESP32","Flash Arduino firmware with occupancy logic","Connect to WiFi and MQTT broker","Set up Twilio for SMS alerts","Mount in bathroom, test with family"]},
  { title:"Fall Detection Wristband", phase:"Phase 2 — Intermediate", color:"#5B8DD9",
    skills:["ESP32 + MPU6050 I2C","Signal processing (threshold detection)","BLE or WiFi comms","3D printed or foam enclosure"],
    desc:"Wearable device with accelerometer. Detects sudden acceleration change consistent with a fall. Sends alert to family phone instantly.",
    why:"MPU6050 is a standard sensor in any IoT/embedded path. This project teaches I2C, signal processing, and real-time edge computing — all core firmware skills.",
    steps:["Interface MPU6050 with ESP32 via I2C","Calibrate fall detection threshold","Implement BLE notification to phone","Design comfortable wearable enclosure","Test and calibrate with family"]},
  { title:"Unified Family Dashboard", phase:"Phase 3 — Full Stack", color:"#5BBD8A",
    skills:["MQTT broker (Mosquitto)","React frontend","Node.js or Python backend","Raspberry Pi deployment"],
    desc:"All sensors feed into a Raspberry Pi running Home Assistant + custom React dashboard. Family members see live status from any phone.",
    why:"Connects IoT hardware skills to software skills. A real deployment on Raspberry Pi — exactly the kind of embedded Linux work that makes you a full-stack IoT engineer.",
    steps:["Set up Mosquitto MQTT on Raspberry Pi","Connect all ESP32 sensors as MQTT publishers","Build React dashboard with live updates","Deploy on local network + Tailscale for remote","Share with family — iterate based on feedback"]},
  { title:"Smart Farm → Healing Garden", phase:"Phase 4 — Vision", color:"#D9A84E",
    skills:["Environmental sensors (same as smart farm)","Plant therapy monitoring","AI anomaly detection","Open-source community platform"],
    desc:"Your smart farming sensor toolkit maps almost directly to therapeutic home environment monitoring. A healing garden space for stroke recovery.",
    why:"This is where your solarpunk vision and this family's needs intersect. Therapeutic gardens have documented benefits for stroke recovery. Your ESP32 + sensor stack from smart farming is the same hardware.",
    steps:["Adapt grow environment sensors to living space","Add plant monitoring to caregiver dashboard","Research horticultural therapy for stroke recovery","Document as open-source project for other families","Publish on blog as a case study"]},
];
